config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]  # Nested since bookmarks belong to lists
  end
  resources :bookmarks, only: [:destroy]  # Direct delete route
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in this list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :restrict_with_error # Prevent deletion if bookmarks exist
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Movie was successfully added to the list.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully removed.', status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: "List was successfully created." # Ensure correct redirect
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h2>Add a Movie to <%= @list.name %></h2>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.association :movie, collection: Movie.all, label_method: :title, value_method: :id, include_blank: "Select a movie" %>
  </div>

  <div class="form-group">
    <%= f.input :comment, placeholder: "Why do you like this movie?" %>
  </div>

  <%= f.submit "Add Movie", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to List", list_path(@list), class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watch List</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
</head>
<body>

  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="/">My Watchlist</a>
    <div>
      <%= link_to "My Lists", lists_path, class: "btn btn-outline-primary" %>
      <%= link_to "New List", new_list_path, class: "btn btn-primary" %>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>

</body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<h1>My Movie Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list) %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new list", new_list_path, class: "btn btn-primary" %>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

<%= form_with model: @list, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Create List", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to lists", lists_path, class: "btn btn-secondary" %>

app/views/lists/show.html.erb
<div class="list-header" style="background-image: url('<%= 'default-bg.jpg' %>');">
  <h1><%= @list.name %></h1>
  <%= link_to 'add', new_list_bookmark_path(@list) %>
</div>

<% @list.bookmarks.each do |bookmark| %>
<div>
<%= bookmark.movie.title %>
<%= image_tag bookmark.movie.poster_url , height:200 %>
<%= bookmark.comment %>
</div>
<% end %>

<style>
.list-header {
  height: 250px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-size: cover;
  background-position: center;
  color: white;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.6);
}
</style>